language: go

branches:
  only:
    - master

go:
  - 1.7.3
jdk:
  - openjdk8

before_install:
  - glide install --strip-vendor
  - go get github.com/mattn/goveralls

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
